include fun_test.mk

$(info words $(NUM_FILES))
$(info word $(SECOND_FILE))
$(info filter $(C_SRCS))
$(info patsubst $(OBJECTS))
$(info addprefix $(OBJ_LIST))
$(info foreach $(OBJ_LIST_2))
$(info dir $(DEFN_DIR))
$(info notdir $(DEFN_BASENAME))
$(info shell $(PASSWD_OWNER))

include macros_test.mk
$(info shell $(PASSWD_SIZE))

include build_steps.mk